example-client:
  message: Hello, local user.
  pronoun:
    check:
      name: Local User
      pronoun: she
      linking-verb: is

spring:
  datasource:
    data-password:
    data-username: SA
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:example-client
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: 192.168.2.220
    username: guest
    password: guest
  profiles: local
#---
# This profile provides full debug of generated SQL and can be very useful for customizing queries.
#spring:
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#  profiles: sql-debug
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
