example-client:
  message: Hello, Chip!  This message has been updated.
  pronoun:
    check:
      name: Chip
      pronoun: they
      linking-verb: are

server:
  port: 8085

spring:
  data:
    rest:
      base-path: /example-api
  datasource:
    data-password:
    data-username: SA
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:example-client
  jpa:
    hibernate:
      ddl-auto: create-drop
  profiles: dev
---
#This profile provides full debug of generated SQL and can be very useful for customizing queries.
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  profiles: sql-debug

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
